name = "minic-compiler"
defaultTargets = ["minic-compiler", "Parser", "parserTests"]
testDriver = "parserTests"

[[lean_lib]]
name = "Scanner"

[[lean_lib]]
name = "Automata"
roots = [
  "Automata.Common",
  "Automata.DFA",
  "Automata.NFA",
  "Automata.Simulation",
  "Automata.SimulationTactics",
  "Automata.Thompson",
  "Automata.Subset"
]

[[lean_lib]]
name = "Parser"

[[lean_exe]]
name = "minic-compiler"
root = "Main"

[[lean_exe]]
name = "parserTests"
root = "Parser.Tests"
